name: golangci-lint
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
permissions:
  contents: read
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      - name: Install Go tools
        run: |
          go get -v golang.org/x/lint/golint
      - name: Lint Go code
        run: |
          golint ./...
      - name: Test Go code
        run: |
          go test -v ./...
